import type {ComposeCart} from '@/modules/cart/domain'
import {delay} from '@/shared/lib/flow/delay'

const cartMock: ComposeCart = {
  typeId: 2,
  markets: [
    {
      champId: 88_637,
      champName: 'Чемпионат Англии. Премьер-лига',
      // champNameEng: 'England Premier League',
      coef: 3.9,
      gameAwayTeamName: 'Арсенал',
      gameHomeTeamName: 'Кристал Пэлэс',
      gameId: 380_836_616,
      gameName: undefined,
      // gameNameEng: undefined,
      gameShortId: 37_495,
      groupId: 1,
      groupName: '1x2',
      id: '380836616-0-1-0',
      isBlocked: false,
      isDependent: false,
      kind: 3,
      name: 'Кристал Пэлэс',
      param: undefined,
      playerId: undefined,
      playerName: undefined,
      sportId: 1,
      sportName: 'Футбол',
      // sportNameEng: 'Football',
      typeId: 1,
    },
    {
      champId: 96_463,
      champName: 'Чемпионат Германии. Бундеслига',
      // champNameEng: 'Germany Bundesliga',
      coef: 4.36,
      gameAwayTeamName: 'Бавария',
      gameHomeTeamName: 'Айнтрахт Франкфурт',
      gameId: 388_456_341,
      gameName: undefined,
      // gameNameEng: undefined,
      gameShortId: 57_472,
      groupId: 1,
      groupName: '1x2',
      id: '388456341-0-2-0',
      isBlocked: false,
      isDependent: false,
      kind: 3,
      name: 'Ничья',
      param: undefined,
      playerId: undefined,
      playerName: undefined,
      sportId: 1,
      sportName: 'Футбол',
      // sportNameEng: 'Football',
      typeId: 2,
    },
    {
      champId: 96_463,
      champName: 'Чемпионат Германии. Бундеслига',
      // champNameEng: 'Germany Bundesliga',
      coef: 4.36,
      gameAwayTeamName: 'Бавария',
      gameHomeTeamName: 'Айнтрахт Франкфурт',
      gameId: 388_456_341,
      gameName: undefined,
      // gameNameEng: undefined,
      gameShortId: 57_472,
      groupId: 1,
      groupName: '1x2',
      id: '388456342-0-2-0',
      isBlocked: false,
      isDependent: false,
      kind: 3,
      name: 'Ничья',
      param: undefined,
      playerId: undefined,
      playerName: undefined,
      sportId: 1,
      sportName: 'Футбол',
      // sportNameEng: 'Football',
      typeId: 2,
    },
  ],
  amount: 100,
  coef: 17.004,
  systemValue: 2,
}

const updateCart = async (cart: ComposeCart): Promise<ComposeCart> => {
  await delay(1000)

  return cartMock
}

export const useCartApiAdapter = () => ({
  updateCart,
})
